package com.crisil.eir.calc.props;

import com.crisil.eir.calc.Discounting;
import com.crisil.eir.calc.amort.AmortisationEngine;
import com.crisil.eir.calc.amort.AmortisationResult;
import com.crisil.eir.calc.amort.AmortisationRow;
import com.crisil.eir.calc.amort.TwoLegResult;
import com.crisil.eir.calc.projection.ContractTerms;
import com.crisil.eir.calc.projection.ConventionSelector;
import com.crisil.eir.calc.projection.DiscountInstrumentProjector;
import com.crisil.eir.calc.projection.FeePosting;
import com.crisil.eir.calc.projection.ProjectionResult;
import com.crisil.eir.calc.projection.ProjectorRegistry;
import com.crisil.eir.calc.projection.ScheduleShape;
import com.crisil.eir.calc.solver.BracketedNewtonSolver;
import com.crisil.eir.calc.solver.SolveRequest;
import com.crisil.eir.calc.solver.SolveResult;
import com.crisil.eir.domain.CashFlow;
import com.crisil.eir.domain.DayCountConvention;
import com.crisil.eir.domain.FeeClassification;
import com.crisil.eir.domain.FlowVector;
import com.crisil.eir.domain.InvariantId;
import com.crisil.eir.domain.InvariantResult;
import com.crisil.eir.domain.Money;
import com.crisil.eir.domain.Precision;
import com.crisil.eir.domain.Rate;
import com.crisil.eir.domain.RateType;
import com.crisil.eir.domain.TimeConvention;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Combinators;

/**
 * The generated instrument space, and the one pipeline every property runs it
 * through.
 *
 * <p>The reference cases prove the engine right on nine specific instruments. This
 * package proves it cannot be wrong in a structurally detectable way on
 * <em>any</em> instrument the projectors can represent, which needs a generator
 * whose range is the range of an Indian bank's book rather than a range chosen to
 * make the properties pass: principal from a 10,000 consumer-durable loan to a
 * 100,000,000 corporate facility, 0.5% to 36% nominal per annum, one period to
 * thirty years, annual through monthly compounding, and a net integral fee of
 * either sign, because a net cost paid is as real as a net fee received and it
 * moves the EIR the other way (invariant INV-2).
 *
 * <h2>Why the ranges stop where they do</h2>
 *
 * <p>Every bound here is either quoted from the task's plausible-contract
 * envelope or derived from a projector's own precondition, and each one is stated
 * so that a reader can tell a deliberate limit from an accident:
 *
 * <ul>
 *   <li><b>Term.</b> One to 360 periods, capped at a thirty-year horizon
 *       ({@code 30 x periodsPerYear}). A 360-period <em>annual</em> schedule is a
 *       360-year loan: representable, and not an instrument, so generating it
 *       would spend the sweep on arithmetic no bank will ever book.</li>
 *   <li><b>Capitalising shapes.</b> {@link ScheduleShape#BULLET} and
 *       {@link ScheduleShape#DISCOUNT_INSTRUMENT} return their whole yield as
 *       accretion, so {@code (1+r)^n} is the price-to-face ratio. It is capped at
 *       {@value #MAX_CAPITALISED_GROWTH_TEXT}: beyond that a discount instrument
 *       prices below one per cent of face, which rounds the issue price towards
 *       zero and produces a target no rate discounts to — an unsolvable vector
 *       generated by the fixture rather than a defect found in the engine.</li>
 *   <li><b>Balloon.</b> Five to sixty per cent of principal. The projector
 *       rejects a terminal lump sum that discounts to at least the principal,
 *       because no positive instalment then exists and the instrument is a bullet
 *       wearing a balloon's name.</li>
 *   <li><b>Step ladders.</b> 1.01 to 1.10 rising, 0.90 to 0.99 falling — the
 *       retail and project-finance ladders, and the projector rejects a factor
 *       pointing the wrong way for the declared shape.</li>
 *   <li><b>{@link ScheduleShape#REVOLVING} is excluded.</b> ACPIR 54 accepts that
 *       no EIR can be determined for a revolver, and the projector says so
 *       through {@link ProjectionResult#futureLegIsWhollySynthetic()}. Sweeping
 *       EIR invariants over an approximation would assert properties of a number
 *       that is not an EIR.</li>
 * </ul>
 *
 * <h2>Nothing here reads a clock</h2>
 *
 * <p>Dates are generated inside a fixed window from fixed endpoints, never from
 * {@code LocalDate.now()}. A fixture that dated a contract from today would assert
 * a moving target, and the replay eighteen months later — the one an auditor is
 * watching — would diverge for reasons that have nothing to do with the engine
 * (invariant DT-1). The window deliberately spans two leap years and admits the
 * 29th, 30th and 31st as disbursement days, because month-end pairs are exactly
 * where day counts and the periodic-index precondition part company.
 */
final class Generators {

    /** 10,000 — the smallest consumer-durable advance worth booking. */
    static final long MIN_PRINCIPAL_PAISE = 1_000_000L;

    /** 100,000,000 — a mid-market corporate facility. */
    static final long MAX_PRINCIPAL_PAISE = 10_000_000_000L;

    /** 0.50% per annum nominal, at the subvention end of a retail book. */
    static final int MIN_NOMINAL_BPS = 50;

    /** 36.00% per annum nominal — a revolving-card rate applied to a term shape. */
    static final int MAX_NOMINAL_BPS = 3600;

    /** Each fee leg runs to 5% of the amount advanced; the two net to either sign. */
    static final int MAX_FEE_BPS = 500;

    /** The price-to-face cap, as text, so that the class javadoc can quote it. */
    static final String MAX_CAPITALISED_GROWTH_TEXT = "100";

    /** Price-to-face floor of 1% for the shapes whose entire return capitalises. */
    static final BigDecimal MAX_CAPITALISED_GROWTH = new BigDecimal(MAX_CAPITALISED_GROWTH_TEXT);

    /** The shapes the standard registry projects from contract terms alone. */
    static final List<ScheduleShape> DERIVABLE_SHAPES = List.of(
        ScheduleShape.ANNUITY_EMI,
        ScheduleShape.STEP_UP,
        ScheduleShape.STEP_DOWN,
        ScheduleShape.BALLOON,
        ScheduleShape.INTEREST_ONLY_BULLET,
        ScheduleShape.BULLET,
        ScheduleShape.DISCOUNT_INSTRUMENT);

    /**
     * The shapes that bill an instalment in every period, and therefore the ones
     * whose vectors can satisfy the periodic-index precondition at all.
     *
     * <p>{@link ScheduleShape#BULLET} and {@link ScheduleShape#DISCOUNT_INSTRUMENT}
     * carry one flow at maturity and nothing in between, so
     * {@link FlowVector#periodicIndexEligible(int)} refuses
     * them and the projection falls back to actual dating. That is correct and it
     * is also why the properties that compare a solved rate against a rate quoted
     * per period draw from this list instead.
     */
    static final List<ScheduleShape> INSTALMENT_SHAPES = List.of(
        ScheduleShape.ANNUITY_EMI,
        ScheduleShape.STEP_UP,
        ScheduleShape.STEP_DOWN,
        ScheduleShape.BALLOON,
        ScheduleShape.INTEREST_ONLY_BULLET);

    /** Half a unit in the last place of a rate stored at twelve decimal places (1.4). */
    private static final BigDecimal HALF_ULP_OF_STORED_RATE = new BigDecimal("5E-13");

    /** Half of INR's minor unit: the largest residue that rounds away at presentation scale. */
    static final BigDecimal HALF_A_PAISE = new BigDecimal("0.005");

    private Generators() {
    }

    // ------------------------------------------------------------- value types

    /**
     * One generated instrument: the terms, the fee postings the rule set resolved,
     * and the two figures a property needs that the terms alone do not carry.
     *
     * @param netIntegralFee fees received less integral costs paid, positive where
     *     the net is income. Held here because {@code ProjectionSupport} computes
     *     it package-privately and a property that re-derived it from the flow
     *     vector would be checking the projector against itself
     * @param amountAdvanced par advanced at presentation scale — the principal for
     *     every shape except a discount instrument, where it is the issue price and
     *     the difference is the whole of the return
     */
    record Contract(
        ContractTerms terms,
        List<FeePosting> fees,
        Money netIntegralFee,
        Money amountAdvanced) {

        Contract {
            fees = List.copyOf(fees);
        }

        /** A one-line description for an assertion message. */
        String label() {
            return terms.shape() + " " + terms.termPeriods() + "x" + terms.periodsPerYear()
                + " principal " + terms.principal().atPresentationScale()
                + " rate " + terms.periodicRate().toPlainString()
                + " netFee " + netIntegralFee.atPresentationScale()
                + " from " + terms.disbursementDate() + " first due " + terms.firstDueDate()
                + " " + terms.dayCount().conventionName()
                + (terms.hasMoratorium() ? " moratorium " + terms.moratoriumPeriods() : "");
        }
    }

    /**
     * The canonical pipeline's output, held whole.
     *
     * <p>Held whole rather than as separate accessors for the same reason the
     * reference-case fixture does it: no property may pair an EIR leg against a
     * contractual leg from a different projection, which produces a fee profile
     * that looks plausible and reconciles to nothing.
     *
     * @param twoLeg {@code null} where the solve produced no rate, which is a
     *     result and not an error — a caller batching a million contracts needs
     *     the failures back as data
     */
    record Pipeline(
        Contract contract,
        ProjectionResult projection,
        SolveResult solve,
        Rate eir,
        AmortisationResult eirLeg,
        AmortisationResult contractualLeg,
        TwoLegResult twoLeg) {

        boolean solved() {
            return twoLeg != null;
        }

        TimeConvention convention() {
            return projection.recommendedConvention();
        }

        boolean underPeriodicIndex() {
            return convention() instanceof TimeConvention.PeriodicIndex;
        }

        /**
         * The largest terminal EIR-leg balance the stored-rate policy can leave
         * behind on this instrument, in the vector's currency.
         *
         * <p>Specification 1.4 requires the roll-forward to use the rate as
         * <em>persisted</em> at twelve decimal places, not as solved at
         * twenty-eight. The persisted rate is therefore up to half a unit in its
         * last place away from the root, and the roll-forward compounds that
         * pricing error to maturity:
         *
         * <pre>
         * |terminal| &lt;= |f'(r)| x 5e-13 x (1+r)^n
         * </pre>
         *
         * <p>where {@code |f'(r)| x 5e-13} bounds the present-value error the
         * rounding admits and {@code (1+r)^n} carries it forward to the last
         * period. On a retail mortgage the product is a millionth of a rupee and
         * invariant TR-1 holds exactly at presentation scale, which is what the
         * reference cases show. On a high-rate, long-tenor instrument it exceeds
         * half a paise, and no rate stored at twelve places can make the leg close
         * at zero — see {@link InvariantBoundaryCasesTest}.
         */
        Money storedRateTerminalBound() {
            BigDecimal carryForward = Precision.onePlusPow(eir.periodic(), terminalTau());
            return Money.of(storedRatePresentValueBound().multiply(carryForward, Precision.WORKING),
                projection.expected().currency());
        }

        /**
         * The present-value error the stored rate admits: {@code |f'(r)| x 5e-13}.
         *
         * <p>The first-order term of the pricing error, and first order is the whole
         * of it at this scale — the second-order term carries {@code (5e-13)^2} and
         * cannot reach the twenty-eighth significant digit the working precision
         * keeps.
         */
        BigDecimal storedRatePresentValueBound() {
            BigDecimal derivative =
                Discounting.derivative(eir.periodic(), projection.expected(), convention()).abs();
            return derivative.multiply(HALF_ULP_OF_STORED_RATE, Precision.WORKING);
        }

        /** Tau at the last accrual boundary — periods under indexing, years under actual dating. */
        BigDecimal terminalTau() {
            BigDecimal tau = BigDecimal.ZERO;
            for (AmortisationRow row : eirLeg.rows()) {
                tau = tau.add(row.accrualExponent(), Precision.WORKING);
            }
            return tau;
        }

        /**
         * Whether the stored-rate policy admits an exactly zero terminal balance on
         * this instrument — that is, whether TR-1 and INV-1 are attainable as
         * literally stated.
         */
        boolean exactTerminalBalanceIsAttainable() {
            return storedRateTerminalBound().abs().amount().compareTo(HALF_A_PAISE) < 0;
        }

        /**
         * Whether the terminal balance the leg actually closed at is inside what
         * rounding the rate for storage can explain.
         *
         * <p>This is the quantity the sweep asserts directly, and it is what makes
         * excluding a TR-1 or INV-1 breach from
         * {@link #unaccountedBreaches()} a redirection rather than a dismissal: the
         * deviation is still checked, against a bound derived from the stored-rate
         * policy instead of against zero.
         */
        boolean terminalResidueIsWithinTheStoredRateBound() {
            BigDecimal allowed = storedRateTerminalBound().abs().amount().max(HALF_A_PAISE);
            return eirLeg.terminalBalance().abs().amount().compareTo(allowed) <= 0;
        }

        /**
         * Breaches that no property in this package accounts for, and which are
         * therefore defects.
         *
         * <p>Two exclusions, both narrow and both exhibited in
         * {@link InvariantBoundaryCasesTest}. INV-2 is excluded because it compares a
         * solved rate against a rate quoted per period, which is only well posed under
         * periodic indexing and only decisive once the fee dominates the billed
         * rounding residue; {@link RateOrderingPropertiesTest} owns it over the
         * population where both hold. TR-1 and INV-1 are excluded only where the leg's
         * closing balance is inside {@link #terminalResidueIsWithinTheStoredRateBound()},
         * which covers two distinct and equally uninteresting causes: a residue that
         * no rate persisted at twelve decimal places could remove, and the one paise
         * that appears when INV-1's two large totals are rounded independently and
         * straddle a rounding boundary. The sweep asserts the residue itself in both
         * cases, so nothing is dismissed here — it is checked somewhere the bound can
         * be stated.
         */
        List<InvariantResult> unaccountedBreaches() {
            boolean explained = terminalResidueIsWithinTheStoredRateBound();
            List<InvariantResult> kept = new ArrayList<>();
            for (InvariantResult breach : twoLeg.breaches()) {
                if (breach.id() == InvariantId.INV_2) {
                    continue;
                }
                if (explained && (breach.id() == InvariantId.TR_1 || breach.id() == InvariantId.INV_1)) {
                    continue;
                }
                kept.add(breach);
            }
            return kept;
        }

        String label() {
            return contract.label() + " | " + convention().label() + " | " + solve.status();
        }
    }

    // -------------------------------------------------------------- pipeline

    /**
     * Projection, solve, both legs, reconciliation — the published seams, in the
     * published order.
     *
     * <p>The contractual leg opens at {@code initialCarryingAmount + netIntegralFee}
     * rather than at {@code terms.principal()}. The two agree on every shape whose
     * par is its principal and differ on a discount instrument, where par is the
     * issue price; deriving par from the projection keeps the pipeline
     * shape-agnostic, and it is exact because both figures are at presentation
     * scale.
     *
     * <p>The rate goes through {@link ConventionSelector#rateUnder} because a
     * contract quotes its rate in the schedule's frequency while the convention the
     * vector licenses may be actual dating, whose {@code periodsPerYear} is one.
     * The EIR leg needs no adaptation: the solver returns the rate in the
     * convention's units already.
     */
    static Pipeline run(Contract contract) {
        ContractTerms terms = contract.terms();
        ProjectionResult projection = ProjectorRegistry.standard().project(terms, contract.fees());
        SolveResult solve = new BracketedNewtonSolver().solve(SolveRequest.of(
            projection.expected(),
            projection.initialCarryingAmount(),
            projection.recommendedConvention(),
            terms.periodicRate()));
        if (!solve.hasRate()) {
            return new Pipeline(contract, projection, solve, null, null, null, null);
        }
        Rate eir = solve.rateOrThrow();
        AmortisationResult eirLeg = AmortisationEngine.eirLeg(
            projection.initialCarryingAmount(), eir, projection.expected(),
            projection.recommendedConvention());
        AmortisationResult contractualLeg = AmortisationEngine.contractualLeg(
            projection.initialCarryingAmount().plus(contract.netIntegralFee()),
            ConventionSelector.rateUnder(projection.recommendedConvention(), terms.contractualRate()),
            projection.contractual(),
            projection.recommendedConvention());
        TwoLegResult twoLeg = TwoLegResult.reconcile(
            eirLeg, contractualLeg, eir, terms.contractualRate(), contract.netIntegralFee());
        return new Pipeline(contract, projection, solve, eir, eirLeg, contractualLeg, twoLeg);
    }

    /**
     * The same instrument with every integral fee stripped out.
     *
     * <p>The comparator invariant INV-2 is really about: the rate the billed
     * schedule yields on its own. Solving it from the same vector removes the
     * billed-rounding residue from the comparison, because both solves see the same
     * rounded schedule.
     */
    static Contract withoutIntegralFees(Contract contract) {
        List<FeePosting> kept = new ArrayList<>();
        for (FeePosting fee : contract.fees()) {
            if (!fee.entersInitialCarryingAmount()) {
                kept.add(fee);
            }
        }
        return new Contract(contract.terms(), kept,
            Money.zero(contract.terms().currency()), contract.amountAdvanced());
    }

    // ------------------------------------------------------------ arbitraries

    /** The full instrument space: every derivable shape, both fee signs, both conventions. */
    static Arbitrary<Contract> contracts() {
        return skeletons(Arbitraries.of(DERIVABLE_SHAPES), disbursementDates(), brokenPeriodDays())
            .flatMap(skeleton -> dress(skeleton, true));
    }

    /**
     * Contracts whose vectors are periodic-index eligible by construction: an
     * instalment in every period, a whole first period, and a disbursement day of
     * the month that survives {@code plusMonths} unchanged.
     *
     * <p>Used by the properties that compare a solved rate against a rate quoted per
     * period, and by the ones that assert a per-period interest profile. Under
     * actual dating neither comparison is well posed: tau is a year fraction there,
     * a 28-day February and a 31-day March accrue different amounts from the same
     * balance, and the contractual rate would have to be restated before it could
     * be compared at all.
     */
    static Arbitrary<Contract> periodicIndexContracts() {
        return skeletons(Arbitraries.of(INSTALMENT_SHAPES), alignedDisbursementDates(),
            Arbitraries.just(0)).flatMap(skeleton -> dress(skeleton, false));
    }

    /** Level-annuity contracts on aligned dates — the one shape with a monotone profile. */
    static Arbitrary<Contract> levelAnnuities() {
        return skeletons(Arbitraries.just(ScheduleShape.ANNUITY_EMI), alignedDisbursementDates(),
            Arbitraries.just(0))
            .flatMap(skeleton -> dress(skeleton, false));
    }

    /**
     * Contracts whose net integral fee is large enough for its sign to survive the
     * billed schedule's own rounding residue.
     *
     * <p>Invariant INV-2 orders the EIR against the contractual rate by the sign of
     * the net fee, and under {@code LMS_AUTHORITATIVE} the billed instalment is the
     * true annuity payment rounded to paise. Reference case 1 bills 47,073.47
     * against 47,073.472223, and over 24 periods that shortfall compounds to a
     * 0.059969 residue: the schedule's own yield is already a few parts in 10^8
     * below the contractual rate before any fee is considered. A fee smaller than
     * that residue orders the rates the other way and INV-2 fails on an instrument
     * where nothing is wrong.
     *
     * <p>The floor is therefore derived rather than picked: the billed rounding can
     * move total cash by at most half a paise per instalment, so a net fee of ten
     * times {@code 0.005 x periods}, plus a rupee, dominates it with an order of
     * magnitude to spare.
     */
    static Arbitrary<Contract> materiallyFeeBearingPeriodicIndexContracts() {
        return periodicIndexContracts().filter(Generators::feeDominatesBilledRounding);
    }

    /** Contracts carrying a net fee of at least a rupee, of either sign. */
    static Arbitrary<Contract> feeBearingContracts() {
        return contracts().filter(contract ->
            contract.netIntegralFee().abs().amount().compareTo(BigDecimal.ONE) >= 0);
    }

    static boolean feeDominatesBilledRounding(Contract contract) {
        BigDecimal floor = BigDecimal.ONE.add(
            new BigDecimal("0.05").multiply(BigDecimal.valueOf(contract.terms().termPeriods())));
        return contract.netIntegralFee().abs().amount().compareTo(floor) >= 0;
    }

    // ------------------------------------------------------------- skeletons

    /**
     * Everything that fixes the schedule's geometry, before the shape-specific
     * features and the fees are attached.
     */
    private record Skeleton(
        Money principal,
        Rate rate,
        int periodsPerYear,
        int termPeriods,
        DayCountConvention dayCount,
        ScheduleShape shape,
        LocalDate disbursement,
        int brokenPeriodDays) {

        LocalDate firstDue() {
            return disbursement.plusMonths(12 / periodsPerYear).plusDays(brokenPeriodDays);
        }
    }

    /** Shape-specific features, applied only where the declared shape needs them. */
    private record Features(int stepBps, int balloonPercent, int moratoriumPeriods, boolean capitalises) {
    }

    private static Arbitrary<Skeleton> skeletons(
        Arbitrary<ScheduleShape> shapes, Arbitrary<LocalDate> dates, Arbitrary<Integer> brokenDays) {

        return Combinators.combine(
                Arbitraries.longs().between(MIN_PRINCIPAL_PAISE, MAX_PRINCIPAL_PAISE),
                Arbitraries.integers().between(MIN_NOMINAL_BPS, MAX_NOMINAL_BPS),
                Arbitraries.of(1, 2, 4, 12),
                Arbitraries.integers().between(1, 360),
                Arbitraries.of(DayCountConvention.values()),
                shapes,
                dates,
                brokenDays)
            .as(Generators::skeleton);
    }

    private static Skeleton skeleton(
        long principalPaise,
        int nominalBps,
        int periodsPerYear,
        int requestedTerm,
        DayCountConvention dayCount,
        ScheduleShape shape,
        LocalDate disbursement,
        int brokenPeriodDays) {

        BigDecimal periodic = BigDecimal.valueOf(nominalBps, 4)
            .divide(BigDecimal.valueOf(periodsPerYear), Precision.WORKING);
        Rate rate = Rate.periodic(periodic, periodsPerYear);
        int horizonCap = Math.min(360, 30 * periodsPerYear);
        int term = Math.min(requestedTerm, horizonCap);
        if (shape == ScheduleShape.BULLET || shape == ScheduleShape.DISCOUNT_INSTRUMENT) {
            term = Math.min(term, termWithinCapitalisedGrowth(rate.periodic(), term));
        }
        return new Skeleton(
            Money.of(BigDecimal.valueOf(principalPaise, 2), Money.INR),
            rate, periodsPerYear, term, dayCount, shape, disbursement, brokenPeriodDays);
    }

    /**
     * The longest term over which {@code (1+r)^n} stays inside the capitalised
     * growth cap, by binary search on the exact power.
     *
     * <p>Computed rather than approximated because the whole point of this module
     * is that no arithmetic in it is done in binary floating point — a generator
     * that reached for {@code Math.log} to size its own range would be the one
     * place in the suite that did.
     */
    private static int termWithinCapitalisedGrowth(BigDecimal periodic, int ceiling) {
        if (Precision.onePlusPow(periodic, ceiling).compareTo(MAX_CAPITALISED_GROWTH) <= 0) {
            return ceiling;
        }
        int low = 1;
        int high = ceiling;
        while (low < high) {
            int mid = (low + high + 1) / 2;
            if (Precision.onePlusPow(periodic, mid).compareTo(MAX_CAPITALISED_GROWTH) <= 0) {
                low = mid;
            } else {
                high = mid - 1;
            }
        }
        return low;
    }

    private static Arbitrary<Contract> dress(Skeleton skeleton, boolean admitMoratorium) {
        return features(skeleton, admitMoratorium).flatMap(features -> dress(skeleton, features));
    }

    private static Arbitrary<Contract> dress(Skeleton skeleton, Features features) {
        ContractTerms terms = terms(skeleton, features);
        Money advanced = advanced(terms);
        return Combinators.combine(
                Arbitraries.integers().between(0, MAX_FEE_BPS),
                Arbitraries.integers().between(0, MAX_FEE_BPS))
            .as((receivedBps, paidBps) -> contract(terms, advanced, receivedBps, paidBps));
    }

    /**
     * A moratorium is generated on one contract in three rather than uniformly.
     *
     * <p>It voids the periodic-index precondition on its own — there is no cash in
     * the leading periods, so the first accrual boundary spans several of them — and
     * a uniform draw would push most of the annuity population onto the actual-date
     * path and starve the cheaper convention of coverage. Both paths need sweeping.
     */
    private static Arbitrary<Features> features(Skeleton skeleton, boolean admitMoratorium) {
        int ceiling = Math.max(0, Math.min(12, skeleton.termPeriods() - 1));
        Arbitrary<Integer> moratorium = admitMoratorium && ceiling > 0
            ? Arbitraries.of(0, 0, 0, 0, 1, 2, 3, 6, 12).map(periods -> Math.min(periods, ceiling))
            : Arbitraries.just(0);
        return Combinators.combine(
                Arbitraries.integers().between(100, 1000),
                Arbitraries.integers().between(5, 60),
                moratorium,
                Arbitraries.of(true, false))
            .as(Features::new);
    }

    private static ContractTerms terms(Skeleton skeleton, Features features) {
        ContractTerms terms = ContractTerms.of(
            skeleton.principal(), skeleton.rate(), skeleton.termPeriods(), skeleton.periodsPerYear(),
            skeleton.disbursement(), skeleton.firstDue(), skeleton.dayCount(), skeleton.shape(),
            RateType.FIXED);
        return switch (skeleton.shape()) {
            case STEP_UP -> terms.withStepFactor(
                BigDecimal.ONE.add(BigDecimal.valueOf(features.stepBps(), 4)));
            case STEP_DOWN -> terms.withStepFactor(
                BigDecimal.ONE.subtract(BigDecimal.valueOf(features.stepBps(), 4)));
            case BALLOON -> terms.withBalloon(
                skeleton.principal().times(BigDecimal.valueOf(features.balloonPercent(), 2))
                    .atPresentationScale());
            case ANNUITY_EMI -> features.moratoriumPeriods() > 0
                ? terms.withMoratorium(features.moratoriumPeriods(), features.capitalises())
                : terms;
            default -> terms;
        };
    }

    /**
     * Par advanced: the principal, or a discount instrument's issue price.
     *
     * <p>Taken from the projector's own public pricing method rather than
     * recomputed, because a fixture that priced the instrument itself would be
     * asserting its own arithmetic and would drift from the engine's the first time
     * either changed.
     */
    private static Money advanced(ContractTerms terms) {
        if (terms.shape() == ScheduleShape.DISCOUNT_INSTRUMENT) {
            // issuePrice is a derived intermediate and comes back at working
            // precision; presented here because Contract.amountAdvanced is declared
            // at presentation scale and because that is the figure the projector's
            // own inception leg and initial carrying amount are stated at.
            return new DiscountInstrumentProjector().issuePrice(terms).atPresentationScale();
        }
        return terms.principal().atPresentationScale();
    }

    private static Contract contract(ContractTerms terms, Money advanced, int receivedBps, int paidBps) {
        LocalDate postedOn = terms.disbursementDate();
        Money received = advanced.times(BigDecimal.valueOf(receivedBps, 4)).atPresentationScale();
        Money paid = advanced.times(BigDecimal.valueOf(paidBps, 4)).atPresentationScale();
        List<FeePosting> fees = new ArrayList<>();
        if (received.isPositive()) {
            fees.add(FeePosting.received("PROCESSING_FEE", received, postedOn, FeeClassification.INTEGRAL));
        }
        if (paid.isPositive()) {
            fees.add(FeePosting.paid("DSA_COMMISSION", paid, postedOn, FeeClassification.INTEGRAL, "SELLING"));
        }
        // An as-incurred servicing charge rides along on every contract. It is a real
        // posting that simply does not belong to the initial carrying amount, and its
        // presence is what makes IC-1 an assertion about classification rather than
        // about addition (specification 3.2).
        fees.add(FeePosting.received("SERVICING_FEE",
            advanced.times(new BigDecimal("0.001")).atPresentationScale(), postedOn,
            FeeClassification.AS_INCURRED));
        return new Contract(terms, fees, received.minus(paid), advanced);
    }

    // ------------------------------------------------------------------ dates

    /**
     * A four-year window spanning two leap years, with every day of the month in
     * range — including the 29th, 30th and 31st, where {@code plusMonths} clamps
     * and the periodic-index precondition breaks.
     */
    static Arbitrary<LocalDate> disbursementDates() {
        return Combinators.combine(
                Arbitraries.integers().between(2024, 2028),
                Arbitraries.integers().between(1, 12),
                Arbitraries.integers().between(1, 31))
            .as(Generators::dateClampedToMonth);
    }

    /**
     * The same window restricted to days that survive {@code plusMonths}
     * unchanged, so that {@code dueDate(i)} lands exactly on
     * {@code anchor.plusMonths(monthsPerPeriod * i)} and the vector is
     * periodic-index eligible.
     */
    static Arbitrary<LocalDate> alignedDisbursementDates() {
        return Combinators.combine(
                Arbitraries.integers().between(2024, 2028),
                Arbitraries.integers().between(1, 12),
                Arbitraries.integers().between(1, 28))
            .as(LocalDate::of);
    }

    /** Days of broken first period: mostly none, sometimes a stub that voids periodic indexing. */
    static Arbitrary<Integer> brokenPeriodDays() {
        return Arbitraries.of(0, 0, 0, 0, 3, 11, 17, 26);
    }

    private static LocalDate dateClampedToMonth(int year, int month, int day) {
        LocalDate first = LocalDate.of(year, month, 1);
        return LocalDate.of(year, month, Math.min(day, first.lengthOfMonth()));
    }

    // ---------------------------------------------------------- serialisation

    /**
     * The whole computation as one canonical string.
     *
     * <p>Every figure is written with {@link BigDecimal#toPlainString()}, which is
     * locale-independent and scale-preserving, so two runs that agree here agree
     * bit for bit and not merely to some tolerance. Scale is deliberately
     * preserved: {@code 0.00} and {@code 0} are the same number and are not the
     * same published figure, and a determinism test that normalised them away
     * would stop being a determinism test.
     */
    static String canonicalise(Pipeline pipeline) {
        StringBuilder text = new StringBuilder(4096);
        Contract contract = pipeline.contract();
        text.append("contract=").append(contract.label()).append('\n');
        for (FeePosting fee : contract.fees()) {
            text.append("fee=").append(fee.feeCode()).append(' ')
                .append(fee.amount().amount().toPlainString()).append(' ')
                .append(fee.classification()).append('\n');
        }
        text.append("ica=").append(pipeline.projection().initialCarryingAmount().amount().toPlainString())
            .append(" convention=").append(pipeline.convention().label())
            .append(" syntheticFutureLeg=").append(pipeline.projection().futureLegIsWhollySynthetic())
            .append('\n');
        appendVector(text, "contractual", pipeline.projection().contractual());
        appendVector(text, "expected", pipeline.projection().expected());
        for (InvariantResult result : pipeline.projection().invariants()) {
            appendInvariant(text, result);
        }
        text.append("solve=").append(pipeline.solve().status())
            .append(' ').append(pipeline.solve().method())
            .append(" iterations=").append(pipeline.solve().iterations())
            .append(" roots=").append(pipeline.solve().candidateRootCount())
            .append('\n');
        if (!pipeline.solved()) {
            return text.append("diagnostic=").append(pipeline.solve().diagnostic()).append('\n').toString();
        }
        text.append("eir=").append(pipeline.eir().periodic().toPlainString())
            .append(" x").append(pipeline.eir().periodsPerYear())
            .append(" effectiveAnnual=").append(pipeline.eir().effectiveAnnual().toPlainString())
            .append(" nominalAnnual=").append(pipeline.eir().nominalAnnual().toPlainString())
            .append(" residual=").append(pipeline.solve().residualAtStoredRate().toPlainString())
            .append('\n');
        appendLeg(text, "eirLeg", pipeline.eirLeg());
        appendLeg(text, "contractualLeg", pipeline.contractualLeg());
        for (InvariantResult result : pipeline.twoLeg().invariants()) {
            appendInvariant(text, result);
        }
        text.append("netFeeRecognised=")
            .append(pipeline.twoLeg().netFeeRecognised().amount().toPlainString())
            .append(" contractualResidue=")
            .append(pipeline.twoLeg().contractualResidue().amount().toPlainString())
            .append('\n');
        return text.toString();
    }

    private static void appendVector(StringBuilder text, String name, FlowVector vector) {
        text.append(name).append(" anchor=").append(vector.anchorDate())
            .append(" size=").append(vector.size()).append('\n');
        for (CashFlow flow : vector.flows()) {
            text.append("  ").append(name).append(' ').append(flow.date()).append(" p")
                .append(flow.periodIndex()).append(' ').append(flow.kind()).append(' ')
                .append(flow.amount().amount().toPlainString()).append('\n');
        }
    }

    private static void appendLeg(StringBuilder text, String name, AmortisationResult leg) {
        text.append(name).append(" periods=").append(leg.periods())
            .append(" totalInterest=").append(leg.totalInterest().amount().toPlainString())
            .append(" totalCash=").append(leg.totalCash().amount().toPlainString())
            .append(" terminal=").append(leg.terminalBalance().amount().toPlainString())
            .append('\n');
        for (AmortisationRow row : leg.rows()) {
            text.append("  ").append(name).append(" p").append(row.period()).append(' ')
                .append(row.date()).append(" dtau=").append(row.accrualExponent().toPlainString())
                .append(" open=").append(row.openingGca().amount().toPlainString())
                .append(" interest=").append(row.eirInterest().amount().toPlainString())
                .append(" cash=").append(row.cashReceived().amount().toPlainString())
                .append(" close=").append(row.closingGca().amount().toPlainString())
                .append('\n');
        }
    }

    private static void appendInvariant(StringBuilder text, InvariantResult result) {
        text.append("invariant=").append(result.id()).append(' ').append(result.satisfied())
            .append(" deviation=")
            .append(result.deviation() == null ? "none" : result.deviation().toPlainString())
            .append(" detail=").append(result.detail()).append('\n');
    }
}
